#tomcat端口号
server:
  port: 8080
  servlet:
    context-path: /UserModel
    jsp:
      init-parameters:
        development: true
spring:
  #有两个配置文件中，只会加载最后一个
#  application:
#    name: UserModel #在注册中心中显示的名字
  #mvc视图解析器
  mvc:
    view:
      prefix: /
      suffix: .jsp
  #数据源
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mydatabase?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource

#  datasource:
#    master: #这个key自定义，后边要用
#      jdbcUrl: jdbc:mysql://192.168.234.110:3306/baizhi?useUnicode=true&characterEncoding=utf8
#      driver-class-name: com.mysql.jdbc.Driver
#      username: root
#      password: 123456
#      type: com.alibaba.druid.pool.DruidDataSource
#    slave1:
#      jdbcUrl: jdbc:mysql://192.168.234.111:3306/baizhi?useUnicode=true&characterEncoding=utf8
#      driver-class-name: com.mysql.jdbc.Driver
#      username: root
#      password: 123456
#      type: com.alibaba.druid.pool.DruidDataSource
#    slave2:
#      jdbcUrl: jdbc:mysql://192.168.234.112:3306/baizhi?useUnicode=true&characterEncoding=utf8
#      driver-class-name: com.mysql.jdbc.Driver
#      username: root
#      password: 123456
#      type: com.alibaba.druid.pool.DruidDataSource

  #文件上传
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  #redis
#  redis:
#    database: 0
#    host: 192.168.234.15
#    port: 6397
#    sentinel:

#mybatis配置
mybatis:
  mapper-locations: classpath:com/baizhi/um/dao/*Mapper.xml
  type-aliases-package: com.baizhi.um.entity
  executor-type: batch  #批处理
  #开启二级缓存
#  configuration:
#    cache-enabled: true

#FastDFS
fdfs:
  tracker-list: 192.168.234.100:22122, 192.168.234.101:22122,192.168.234.102:22122
  thumb-image:
    width: 100
    height: 100

#在web页面暴露所有endpoint
management:
  endpoints:
    jmx:
      exposure:
        include: '*'
eureka:
  client:
    service-url:
      #服务端地址
      defaultZone: http://localhost:8883/EurekaServer/eureka
  instance:
    #设置ture，表示在注册中心显示ip，而不是计算机名
    prefer-ip-address: true
#自定义配置信息
#user:
#  userUrl: http://localhost:8881/UserServer

